"""Convert PNG images generated by the Jupyter Book build to lossy WebP,
rewrite references in the built HTML, and delete the original PNGs."""

from pathlib import Path

from PIL import Image


def optimize(docs_dir: str | Path = "docs", quality: int = 85) -> None:
    docs_dir = Path(docs_dir)
    images_dir = docs_dir / "_images"
    if not images_dir.is_dir():
        print(f"[optimize_images] no {images_dir}, skipping")
        return

    pngs = sorted(images_dir.glob("*.png"))
    if not pngs:
        print(f"[optimize_images] no PNGs in {images_dir}, skipping")
        return

    rename_map: dict[str, str] = {}
    before_bytes = 0
    after_bytes = 0
    for png in pngs:
        webp = png.with_suffix(".webp")
        img = Image.open(png)
        img.save(webp, format="WEBP", quality=quality)
        before_bytes += png.stat().st_size
        after_bytes += webp.stat().st_size
        rename_map[png.name] = webp.name

    html_files = list(docs_dir.rglob("*.html"))
    rewrites = 0
    for html in html_files:
        text = html.read_text(encoding="utf-8")
        new_text = text
        for old, new in rename_map.items():
            new_text = new_text.replace(old, new)
        if new_text != text:
            html.write_text(new_text, encoding="utf-8")
            rewrites += 1

    for png in pngs:
        png.unlink()

    print(
        f"[optimize_images] converted {len(pngs)} PNGs "
        f"({before_bytes/1024:.0f} KiB -> {after_bytes/1024:.0f} KiB), "
        f"rewrote {rewrites} HTML file(s)"
    )


if __name__ == "__main__":
    optimize()
